"##==================================================##
"#          *** ALBERT752           VIM ***           #
"##==================================================##
set relativenumber
set nu
set ruler
set showcmd
let mapleader = ","
set ttimeout
set notimeout
set ts=4
set smartindent
set autoindent
set shiftwidth=4
set tw=79
set showmatch
syntax on
filetype plugin on
set nocompatible


" Keymaps
" -> Window Management
map <C-J> <C-W>j<C-W>_
map <C-K> <C-W>k<C-W>_
map <C-H> <C-W>h<C-W>_
map <C-L> <C-W>l<C-W>_
nnoremap <C-t> :tabnew<cr>

" -> Exit parenthesis
inoremap <C-e> <C-o>A

" IDE functionality
" -> Basics
inoremap <NUL> <Esc>/<++><Enter>"_c4l
vnoremap <NUL> <Esc>/<++><Enter>"_c4l
map <NUL> <Esc>/<++><Enter>"_c4l
inoremap ;pl 

" -> LaTeX
"	-> Basic document formating
autocmd FileType plaintex  inoremap ;be \begin{}<Enter><++><Enter>\end<Esc>/}<Enter>i
"	-> Chart functionality
autocmd FileType plaintex inoremap ;cno \node [, <++> = <++>] (<++>) {<++>};<Esc>28hi
"	-> Style properties
autocmd FileType plaintex inoremap ;it \textit{}<Esc>/}<Enter>i  
autocmd FileType plaintex inoremap ;bd \textbf{}<Esc>/}<Enter>i  

" -> Python3
autocmd FileType python inoremap ;fun def  (<++>):<Enter><++><Esc>?def<Enter>4li
autocmd FileType python inoremap ;nm if __name__ == '__main__':<Enter>
autocmd FileType python inoremap ;cl class  :<Enter>def __init__(self<++>):<Enter><++><Enter><Enter><BS><++><Esc>4khi
autocmd FileType python inoremap ;pp from pprint import pprint as pp

" -> Vim
autocmd FileType vim inoremap ;ide autocmd FileType   inoremap <++><Esc>14hi

" -> JavaScript
let g:javascript_plugin_jsdoc = 1
let g:javascript_plugin_ngdoc = 1
let g:javascript_plugin_flow = 1

" -> Markdown Syntax
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_conceal = 0
autocmd FileType markdown inoremap ;img ![](./<++>)<Esc>8hi  
autocmd FileType markdown inoremap ;lk [](./<++>)<Esc>8hi  

"
" enable code folding
"augroup javascript_folding
	"au!
	"au FileType javascript setlocal foldmethod=syntax
"augroup END
"" concealing characters
"let g:javascript_conceal_function             = "ƒ"
"let g:javascript_conceal_null                 = "ø"
"let g:javascript_conceal_this                 = "@"
"let g:javascript_conceal_return               = "⇚"
"let g:javascript_conceal_undefined            = "¿"
"let g:javascript_conceal_NaN                  = "ℕ"
"let g:javascript_conceal_prototype            = "¶"
"let g:javascript_conceal_static               = "•"
"let g:javascript_conceal_super                = "Ω"
"let g:javascript_conceal_arrow_function       = "⇒"
"let g:javascript_conceal_noarg_arrow_function = "🞅"
"let g:javascript_conceal_underscore_arrow_function = "🞅"

" Pathogen Enable
execute pathogen#infect()
syntax on
filetype plugin indent on


" Bar settings 
set laststatus=2

" Python
let g:python_highlight_all = 1

" Nerd-Tree
map <C-t> :NERDTreeToggle<CR>
autocmd StdinReadPre * let s:std_in=autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif 


