#!/bin/bash - 
#===============================================================================
#
#          FILE: battery.sh
# 
#         USAGE: ./battery.sh 
# 
#   DESCRIPTION: 
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: YOUR NAME (), 
#  ORGANIZATION: 
#       CREATED: 09/16/2020 23:32
#      REVISION:  ---
#===============================================================================

set -o nounset                              # Treat unset variables as an error
percentage=$(acpi | grep -o "[0-9]\+%" | sed "s/%//")

if [ $percentage -le 25 ]
then
    icon='<span color="#cc241d"></span>' 
elif [ $percentage -le 50 ]
then
    icon='<span color="#d79921"></span>'
elif [ $percentage -le 75 ]
then
    icon='<span color="#98971a"></span>'
else
    icon='<span color="#98971a"></span>'
fi

value=$(acpi | grep -o "[0-9]\+%, [0-9]\+:[0-9]\+" | sed "s/, / (/" | sed "s/$/)/")

echo "$icon <span color='#ebdbb2'>$value</span>"


